#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Verification Plan builder for the risc_v (CV32E40P) project.

The HTML skeleton (style block, thead, title row, header row) is taken
*verbatim* from the provided plan template (plantemplet/*.html) so the
generated plan is structurally identical to the authoritative template.

Only the data rows (and the project title) are generated here, from the
master requirement table below. Component names follow the UVM
architecture diagram of the project exactly:
  sys_ctrl_agent (active: sequencer/driver/input_monitor)
  if_agent (active: sequencer/driver/input_monitor -> OBI slave model)
  if_passive_agent (output_monitor)
  lsu_agent (active: sequencer/driver/input_monitor -> OBI slave model)
  lsu_passive_agent (output_monitor)
  rvfi_monitor (internal_state_monitor)
  ref_model (subscriber), coverage (subscriber), uvm_scoreboard
  sva_module (bind cv32e40p_top), v_sqr, virtual_sequences, env_cfg
  interfaces: sys_ctrl_vif, if_vif, lsu_vif, rvfi_vif
"""

import re, html, os, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_DIR = os.path.join(HERE, "..", "plantemplet")

TITLE = "risc_v"
NUM_COLS = 26  # A..Z as in template

# ---------------------------------------------------------------------------
# Master requirement table
#   id        requirement ID (shared across all sheets -> traceability)
#   desc      Design Requirement Description (repeated verbatim in every sheet,
#             exactly like the DW_apb template does)
#   note      System-sheet implementation note (column C of System.html)
#   comp      component name(s) (System sheet column D)
#   gen / gen_obj                     -> Generation_ sheet columns C/D
#   chk / chk_prop / chk_cmt          -> Checking_   sheet columns C/D/E
#   cov / cov_cg                      -> Coverage_   sheet columns C/D
# ---------------------------------------------------------------------------
R = [
# ============================ SYSTEM / RESET / CLOCK =========================
dict(id="risc_sys_00",
 desc="DUT is cv32e40p_top with default parameters (COREV_PULP=0, COREV_CLUSTER=0, FPU=0, FPU_ADDMUL_LAT=0, FPU_OTHERS_LAT=0, ZFINX=0, NUM_MHPMCOUNTERS=1). Effective ISA: RV32I + M (the C, Zicsr, Zicntr and Zifencei extensions exist in hardware but are outside the verification goal). mimpid = 0.",
 note="top_tb instantiates rtl/cv32e40p_top.sv and verifies the core as a whole at top level.",
 comp="top_tb, cv32e40p_top"),
dict(id="risc_sys_01",
 desc="Full port list of cv32e40p_top must be connected and observed: clk_i, rst_ni, pulp_clock_en_i, scan_cg_en_i, boot_addr_i, mtvec_addr_i, dm_halt_addr_i, hart_id_i, dm_exception_addr_i, instr_{req_o,gnt_i,rvalid_i,addr_o,rdata_i}, data_{req_o,gnt_i,rvalid_i,we_o,be_o,addr_o,wdata_o,rdata_i}, irq_i, irq_ack_o, irq_id_o, debug_req_i, debug_{havereset,running,halted}_o, fetch_enable_i, core_sleep_o.",
 note="Four virtual interfaces wrap the pins: sys_ctrl_vif, if_vif, lsu_vif and rvfi_vif (internal probes).",
 comp="top_tb, sys_ctrl_agent, if_agent, lsu_agent, rvfi_monitor"),
dict(id="risc_sys_02",
 desc="rst_ni is an asynchronous active-low reset. While rst_ni=0 (and until fetch_enable_i is sampled high) the core output drivers must be inactive: instr_req_o=0 and data_req_o=0, and the internal clock is gated by the sleep unit, so the core performs no activity.",
 note="Apply async assert/de-assert at arbitrary times (also mid-test).",
 comp="sys_ctrl_agent, if_passive_agent, lsu_passive_agent",
 chk="check that during rst_ni==0 and until fetch_enable, instr_req_o==0 and data_req_o==0 at every clk_i edge",
 chk_prop="sys_reset_no_req_prop",
 chk_cmt="SVA inside if_passive_agent.output_monitor / lsu_passive_agent.output_monitor",
 gen="Generate reset with random hold time and random de-assert phase relative to clk_i; apply a single reset at test start and (in dedicated tests) re-assert mid-operation",
 gen_obj="sys_ctrl_init_sequence, sys_ctrl_reset_inject_sequence",
 cov="Cover reset assertion contexts: idle / during IF outstanding transaction / during LSU outstanding transaction / during multicycle DIV / during branch flush",
 cov_cg="reset_context_cg"),
dict(id="risc_sys_03",
 desc="boot_addr_i defines the first program counter after reset (first fetch = boot_addr_i). It must be at least half-word aligned; in this project only word-aligned values are driven. It must not change after the core is enabled via fetch_enable_i.",
 note="",
 comp="sys_ctrl_agent, if_passive_agent",
 chk="check that the first fetch request after fetch_enable targets boot_addr_i",
 chk_prop="sys_boot_addr_prop",
 chk_cmt="SVA inside if_passive_agent.output_monitor, sampling instr_addr_o of the 1st granted request after fetch_enable",
 gen="Randomize boot_addr_i across the legal word-aligned memory window (low / middle / high addresses, incl. address-bit corner values)",
 gen_obj="sys_ctrl_init_sequence (field boot_addr)",
 cov="Cover boot_addr_i corner values: min window, max window, walking-1 pattern on upper address bits",
 cov_cg="boot_addr_cg"),
dict(id="risc_sys_04",
 desc="mtvec_addr_i initializes the mtvec CSR as {mtvec_addr_i[31:8], 6'b0, 2'b01} (256-byte aligned base, vectored mode). All exceptions (incl. illegal instruction) jump to the base address {mtvec[31:8], 8'h00}; only interrupts are vectored (base + 4*ID).",
 note="Exceptions always go to the base, as implemented in cv32e40p_if_stage.sv (EXC_PC_EXCEPTION mux).",
 comp="sys_ctrl_agent, if_passive_agent, uvm_scoreboard",
 chk="check that after an illegal instruction the next fetch request targets {mtvec_addr_i[31:8], 8'h00} (base, not vectored)",
 chk_prop="exc_trap_base_prop",
 chk_cmt="uvm_scoreboard / if_passive_agent observing the fetch redirect",
 gen="Randomize mtvec_addr_i per test over a 256B-aligned window (several distinct bases incl. different upper-byte values to catch base-bit bugs)",
 gen_obj="sys_ctrl_init_sequence (field mtvec_addr)",
 cov="Cover several distinct mtvec base values with at least one trap observed each",
 cov_cg="mtvec_base_cg"),
dict(id="risc_sys_05",
 desc="fetch_enable_i: the first instruction fetch after reset de-assertion must not happen while fetch_enable_i==0; after fetch_enable_i has been 1 for at least one cycle (out of reset) fetching starts permanently, and the value of fetch_enable_i is ignored until the next reset. boot_addr_i / mtvec_addr_i / dm_*_addr_i / hart_id_i must stay stable once the core is enabled.",
 note="The internal clock is gated until fetch_enable_i (sleep unit).",
 comp="sys_ctrl_agent, if_passive_agent",
 chk="check that no instr_req_o pulse occurs between reset de-assertion and the first cycle with fetch_enable_i==1",
 chk_prop="sys_no_fetch_before_fe_prop",
 chk_cmt="SVA inside if_passive_agent.output_monitor",
 gen="Randomize the delay between reset de-assertion and fetch_enable_i rising (0,1,...,N cycles); keep fetch_enable_i high afterwards",
 gen_obj="sys_ctrl_init_sequence (field fe_delay)",
 cov="Cover fetch_enable delay bins: 0 cycles, 1 cycle, 2..8, >8 cycles",
 cov_cg="fetch_enable_delay_cg"),
dict(id="risc_sys_06",
 desc="To keep the core in normal operation, the inputs that belong to out-of-goal features are driven to static values for the entire simulation: irq_i = 32'b0, debug_req_i = 1'b0, pulp_clock_en_i = 1'b0, scan_cg_en_i = 1'b0.",
 note="Static driving only; no checkers or coverage are built for these features.",
 comp="sys_ctrl_agent (driver)"),
dict(id="risc_sys_07",
 desc="Primary outputs of cv32e40p_top must never be X/Z after reset de-assertion while the core is clocked: instr_req_o, instr_addr_o, data_req_o, data_we_o, data_be_o, data_addr_o, data_wdata_o (when driven).",
 note="",
 comp="if_passive_agent, lsu_passive_agent",
 chk="check no X on primary outputs at every clk_i edge when rst_ni==1",
 chk_prop="outputs_no_x_prop",
 chk_cmt="SVA ($isunknown) inside both passive output monitors"),
# ============================ INSTRUCTION FETCH / OBI ======================
dict(id="risc_if_00",
 desc="Instruction fetch OBI handshake: instr_req_o is raised for a fetch and must stay high until instr_gnt_i is sampled high for one cycle (request persistence - a request must never be retracted or its address changed once issued).",
 note="The address phase ends at the gnt cycle; instr_addr_o may change the cycle after.",
 comp="if_agent, if_passive_agent",
 chk="check that instr_req_o stays asserted and instr_addr_o stays stable in every cycle with req==1 && gnt==0",
 chk_prop="if_obi_req_persistence_prop, if_obi_addr_stable_prop",
 chk_cmt="SVA inside if_passive_agent.output_monitor",
 gen="Back-pressure stimulus: hold instr_gnt_i low for 0..K cycles (random, K up to several cycles) per fetch, incl. long stalls, while monitoring stability",
 gen_obj="obi_memory_sequence (if channel)",
 cov="Cover gnt wait-state length bins on IF: 0, 1, 2, 3-7, >7 cycles",
 cov_cg="if_obi_wait_states_cg"),
dict(id="risc_if_01",
 desc="instr_req_o must not combinationally depend on instr_rvalid_i (OBI: no rvalid->req dependency); instr_gnt_i may be high even when there is no request, which must not cause any spurious side effect.",
 note="",
 comp="if_agent, if_passive_agent",
 chk="check that granted-count and valid-count match over the whole test: #(req&&gnt) == #(rvalid) by end of test (no request swallowed, no phantom response accepted)",
 chk_prop="if_obi_trans_match_prop",
 chk_cmt="if_passive_agent transaction counters, compared at end of test",
 gen="Mode where instr_gnt_i is held high continuously for long windows (gnt-before-req), incl. windows with no request pending",
 gen_obj="obi_memory_sequence (gnt_always_high mode)",
 cov="Cover the case gnt_i==1 while req_o==0 on the IF channel",
 cov_cg="if_gnt_before_req_cg"),
dict(id="risc_if_02",
 desc="Response phase: instr_rvalid_i is high for exactly one cycle per granted request; instr_rdata_i is sampled in that cycle. Responses must arrive in issue order (master point of view), possibly one or more cycles after grant; the IF interface can have up to DEPTH=2 outstanding requests.",
 note="The TB memory enforces in-order responses; the core relies on ordering (no IDs).",
 comp="if_agent, if_passive_agent",
 chk="check environment guarantee assertions: rvalid only when a granted outstanding request exists; exactly one rvalid pulse per granted request; rdata stable during its rvalid cycle; responses in issue order",
 chk_prop="if_obi_slave_protocol_prop",
 chk_cmt="Assertions inside if_agent (instr_mem_model) as an environment self-check",
 gen="Randomize rvalid latency 1..L cycles per transaction (L up to stress), incl. separating responses of two outstanding requests",
 gen_obj="obi_memory_sequence (if channel, rvalid delay field)",
 cov="Cover IF outstanding-depth bins: 1 and 2 outstanding fetches; cover rvalid latency bins 1, 2, 3-7, >7",
 cov_cg="if_obi_outstanding_cg, if_obi_rvalid_latency_cg"),
dict(id="risc_if_03",
 desc="Back-to-back fetches: while the prefetch FIFO drains, a new instr_req_o may be issued in the cycle immediately following a gnt; a continuous request stream must be sustained.",
 note="",
 comp="if_agent, if_passive_agent",
 chk="check functional continuity of the fetch stream into the scoreboard instruction queue (no duplicated / lost fetch word observed at retire time)",
 chk_prop="sb_fetch_stream_consistent",
 chk_cmt="uvm_scoreboard (if_passive_agent transaction log vs rvfi_monitor PCs)",
 gen="Zero-wait-state memory windows (gnt at request cycle, rvalid next cycle) interleaved with stalled windows to exercise request re-timing",
 gen_obj="obi_memory_sequence (mixed zero-wait / random_wait modes)",
 cov="Cover consecutive grants on back-to-back cycles (req each cycle, gnt each cycle) on IF",
 cov_cg="if_obi_back2back_cg"),
dict(id="risc_if_04",
 desc="Speculative prefetch: the core may fetch up to DEPTH=2 32-bit words beyond the currently executed code region; the instruction memory model must serve any address without side effects and must tolerate reads past the program end.",
 note="Direct consequence of the prefetch buffer; the TB memory never assumes fetch==execute.",
 comp="if_agent (instr_mem_model)"),
dict(id="risc_if_05",
 desc="Flush on taken jump (JAL/JALR are resolved in the ID stage): the prefetch buffer and IF stage are flushed; the new PC request appears on the instruction-side memory interface in the same cycle the jump is in ID; with zero wait states the jump costs 2 cycles.",
 note="",
 comp="if_passive_agent, uvm_scoreboard",
 chk="check via the scoreboard that the retired-PC stream follows exactly: fall-through PCs never retire after a jump; the target PC retires as the jump successor (JAL: PC+imm; JALR: (rs1+imm) & ~1); the link register rd == PC+4",
 chk_prop="sb_pc_flow_match, sb_jump_link_match",
 chk_cmt="uvm_scoreboard (rvfi_monitor + ref_model)",
 gen="Generate jumps forward/backward incl. small (+/- few words) and large offsets, link regs x0/x1/x5; JALR with odd immediate so the target uses the &~1 rule on a word-aligned address",
 gen_obj="riscv_branch_sequence (jump mode)",
 cov="Cover jump direction x link-register choice x (JALR imm sign) x consecutive-jump patterns",
 cov_cg="jump_cg"),
dict(id="risc_if_06",
 desc="Flush on taken branch (resolved in the EX stage): the IF stage and ID stage are flushed; fetch restarts at the branch target; with zero wait states a taken branch costs 3 cycles; a not-taken branch costs 1 cycle (no stall).",
 note="",
 comp="if_passive_agent, uvm_scoreboard",
 chk="check via the scoreboard that instructions fetched after a taken branch on the fall-through path retire no architectural effect, and the retired-PC stream continues at the branch target (PC+imm)",
 chk_prop="sb_pc_flow_match, sb_flush_clean",
 chk_cmt="uvm_scoreboard",
 gen="Generate all 6 conditional branches with taken/not-taken mixes, forward/backward targets, compare operands producing equal/less/greater incl. sign extremes",
 gen_obj="riscv_branch_sequence",
 cov="Cover each branch x taken/not-taken x direction x operand-relation; cover a taken branch while the target fetch encounters wait states",
 cov_cg="branch_taken_cg, branch_offset_cg, branch_operands_cg, branch_target_wait_cross_cg"),
dict(id="risc_if_07",
 desc="Flush on trap (illegal instruction): the pipeline is flushed and fetch restarts at the mtvec base address; handler code at the base continues normally afterwards.",
 note="",
 comp="if_passive_agent, uvm_scoreboard",
 chk="check that after the trapped instruction, the next retired PC equals the mtvec base and subsequent retired PCs follow the handler program",
 chk_prop="sb_trap_redirect",
 chk_cmt="uvm_scoreboard (via rvfi_monitor), cf. risc_sys_04 / risc_dec_02",
 gen="Generate illegal-instruction injections at random program positions, incl. back-to-back illegals and illegal while IF wait states are active",
 gen_obj="riscv_illegal_sequence",
 cov="Cover trap redirect under IF wait-state stress; cover consecutive traps",
 cov_cg="trap_context_cg"),
dict(id="risc_if_08",
 desc="Stimulus constraint: all generated programs consist of 32-bit instructions only, word-aligned (no RVC encodings), with word-aligned branch/jump targets; programs are bounded and terminate at a defined end-of-program sentinel address recognized by the teardown. The aligner and compressed decoder belong to the never-tested C extension and are exercised only as pass-through hardware.",
 note="No self-modifying code is generated (it would require fence.i, which is omitted from the stimulus).",
 comp="generation constraint (riscv_program)",
 gen="Enforced inside the program builder: only 32-bit encodings from the legal RV32I/M set, all control-transfer targets word-aligned and inside the program window, program ends by jumping to the end-of-program address",
 gen_obj="riscv_program (program builder)"),
dict(id="risc_if_09",
 desc="No instruction-address-misaligned exception exists in this core (the C extension is always enabled), so instruction fetch must never cause a trap; any trap observed on a legal stream is a bug.",
 note="Sanity/anti-check.",
 comp="uvm_scoreboard",
 chk="check that no trap redirect occurs on streams containing only legal instructions",
 chk_prop="sb_no_unexpected_trap",
 chk_cmt="uvm_scoreboard"),
# ============================ LOAD/STORE UNIT / OBI ========================
dict(id="risc_lsu_00",
 desc="Data OBI handshake: data_req_o is raised for load/store and must stay high until data_gnt_i is sampled high; data_addr_o, data_we_o, data_be_o, data_wdata_o are sent together with the request and must stay stable while req==1 && gnt==0.",
 note="",
 comp="lsu_agent, lsu_passive_agent",
 chk="check request persistence and address/control/write-data stability during non-granted cycles",
 chk_prop="lsu_obi_req_persistence_prop, lsu_obi_stable_prop",
 chk_cmt="SVA inside lsu_passive_agent.output_monitor",
 gen="LSU back-pressure: gnt delayed 0..K cycles per transaction incl. multi-cycle stalls",
 gen_obj="obi_memory_sequence (lsu channel)",
 cov="Cover LSU gnt wait-state bins: 0, 1, 2, 3-7, >7",
 cov_cg="lsu_obi_wait_states_cg"),
dict(id="risc_lsu_01",
 desc="Response phase (data side): data_rvalid_i is high for exactly one cycle per granted request and terminates both read and write transactions (for stores data_rdata_i is meaningless). Responses are in issue order; the data interface supports up to 2 outstanding transactions; when responses lag, the core applies back-pressure (EX/WB stall) instead of issuing further requests.",
 note="",
 comp="lsu_agent, lsu_passive_agent",
 chk="check environment guarantees (one rvalid per grant, in-order, no rvalid without outstanding) and that effectively never more than 2 outstanding exist on the data bus",
 chk_prop="lsu_obi_slave_protocol_prop, lsu_max_outstanding_prop",
 chk_cmt="env assertions inside lsu_agent + lsu_passive_agent counter",
 gen="Stress slow-response windows (rvalid delayed K cycles) while a store followed by a load is issued -> forces 2-outstanding saturation",
 gen_obj="obi_memory_sequence (lsu channel, stall mode)",
 cov="Cover data outstanding-depth bins 1 and 2; cover LSU rvalid latency bins 1, 2, 3-7, >7; cover stall during the second phase of a misaligned pair",
 cov_cg="lsu_outstanding_cg, lsu_obi_rvalid_latency_cg, lsu_stall_mid_pair_cg"),
dict(id="risc_lsu_02",
 desc="With zero wait states, Load/Store is handled in 1 bus transaction using both EX and WB stages for 1 cycle each (databook cycle table); a non-word-aligned word transfer, or a halfword transfer crossing a word boundary, takes 2 bus transactions (see risc_lsu_04); a store completes when its rvalid returns. cv.elw is out of scope.",
 note="Informational timing, verified through latency coverage at zero-wait.",
 comp="lsu_passive_agent, uvm_scoreboard"),
dict(id="risc_lsu_03",
 desc="Byte-enable generation per access type and address (from rtl cv32e40p_load_store_unit.sv):\nSW: addr[1:0]=00->4'b1111; misaligned first beat 01->1110, 10->1100, 11->1000; second beat 01->0001, 10->0011, 11->0111.\nSH: 00->0011, 01->0110, 10->1100, 11 (crossing)->first 1000 then 0001.\nSB: 00->0001, 01->0010, 10->0100, 11->1000.\nOnly these patterns may ever appear on data_be_o.",
 note="",
 comp="lsu_passive_agent",
 chk="check data_be_o is one of the legal patterns for the current access-type/address/phase on every granted data transaction",
 chk_prop="lsu_be_legal_prop",
 chk_cmt="SVA/LUT check in lsu_passive_agent.output_monitor (access context taken from the monitor)",
 gen="Generate lw/sw at all 4 offsets, lh/sh at all 4 offsets, lb/lbu/sb at all 4 offsets",
 gen_obj="riscv_lsu_sequence (offset sweep)",
 cov="Cover every legal be pattern per access type x offset",
 cov_cg="lsu_be_pattern_cg"),
dict(id="risc_lsu_04",
 desc="Misaligned handling: the LSU never raises address-misaligned exceptions. A word load/store at addr[1:0]!=00, or a halfword at addr[1:0]==11, is performed as TWO bus transactions; the transfer for the lowest address is issued first, followed by (aligned base+4) with the complementary byte-enables; the memory transfers for the two parts are merged by the core into one load/store view. All other offsets need a single transaction.",
 note="Verified in rtl cv32e40p_load_store_unit.sv (data_misaligned_o, misaligned_st) and the databook LSU chapter.",
 comp="lsu_passive_agent, uvm_scoreboard",
 chk="check that misaligned word/halfword accesses produce exactly two OBI transactions: first beat address == original aligned address with phase-1 be, second beat address == +4 with phase-2 be, and that NO trap redirect happens; check the final loaded value and stored bytes match the golden model",
 chk_prop="lsu_misaligned_order_prop, sb_load_result_match, sb_no_exc_on_misaligned",
 chk_cmt="SVA ordering check in lsu_passive_agent + uvm_scoreboard value check",
 gen="Generate misaligned lw/sw at offsets 1,2,3 and lh/sh at offset 3 (crossing) and offsets 1,2 (non-crossing), incl. back-to-back misaligned pairs",
 gen_obj="riscv_lsu_misaligned_sequence",
 cov="Cover misaligned cases: word@1/@2/@3, half@3, half@1/@2 single-beat; cross with wait states on beat1/beat2",
 cov_cg="lsu_misaligned_cg, misaligned_wait_cross_cg"),
dict(id="risc_lsu_05",
 desc="Store data alignment: data_wdata_o is rotated by wdata_offset = addr[1:0] - reg_offset[1:0] (rtl formula), i.e. 01->{wdata[23:0],wdata[31:24]}, 10->{wdata[15:0],wdata[31:16]}, 11->{wdata[7:0],wdata[31:8]}; the memory applies data_be_o lanes only.",
 note="",
 comp="lsu_passive_agent, uvm_scoreboard",
 chk="check stored bytes in the memory model equal the register content placed at the correct lanes (end-of-test memory compare + store->load readback within the test)",
 chk_prop="sb_store_mem_match",
 chk_cmt="uvm_scoreboard vs golden memory model",
 gen="Generate store value corner pool (0x00000000, 0xFFFFFFFF, 0x80000000, 0x7FFFFFFF, 0xAAAAAAAA, 0x55555555, seq bytes 0x01020304, 0xDEADBEEF) x all offsets",
 gen_obj="riscv_lsu_sequence (data pool)",
 cov="Cover store data corners x offsets x access type",
 cov_cg="lsu_wdata_corners_cg"),
dict(id="risc_lsu_06",
 desc="Load data alignment and extension: LB/LH sign-extend the addressed byte/halfword; LBU/LHU zero-extend; LW returns the full word; for misaligned accesses the two response words are assembled (first-response low bytes kept in rdata_q, combined with the second response) according to the address offset.",
 note="",
 comp="uvm_scoreboard",
 chk="check every retired load: rd == golden sign/zero-extended value computed from the memory image at the effective address (incl. misaligned reassembly)",
 chk_prop="sb_load_result_match",
 chk_cmt="uvm_scoreboard (golden RV32IM model)",
 gen="Generate loads where the loaded byte/halfword has MSB=0 and MSB=1 at every offset, for LB/LBU/LH/LHU",
 gen_obj="riscv_lsu_sequence (sign pool)",
 cov="Cover load sign-extension cases: LB x offset x msb, LH x aligned offset x msb",
 cov_cg="load_sign_ext_cg"),
dict(id="risc_lsu_07",
 desc="Memory consistency: in-order data responses and a single hart imply a load must observe the value of the most recent previously-issued store to the same byte address; the TB memory model commits a store at its rvalid and never reorders.",
 note="No store buffer exists in the core; the end-to-end behavior is still checked explicitly.",
 comp="uvm_scoreboard",
 chk="check store->load same-address readback throughout the test (shadow memory in the scoreboard)",
 chk_prop="sb_mem_consistency",
 chk_cmt="uvm_scoreboard shadow memory",
 gen="Generate store->load (same address, same & different sizes/offsets), load->load, load->store, store->store sequences incl. addresses 1 word apart",
 gen_obj="riscv_mem_b2b_sequence",
 cov="Cover back-to-back memory patterns: st->ld same addr, st->ld overlapping halfword/byte lanes, ld->st, st->st, ld->ld",
 cov_cg="mem_b2b_cg"),
dict(id="risc_lsu_08",
 desc="Flushed instructions must not affect the data bus: loads/stores younger than a taken branch, jump, or trap (still in IF/ID) are killed before their request phase - no spurious data_req_o from flushed instructions may appear.",
 note="",
 comp="lsu_passive_agent, uvm_scoreboard",
 chk="check that the data-bus transaction stream matches exactly the loads/stores that retire per the reference model (no extra, no missing transactions)",
 chk_prop="sb_lsu_trans_stream_match",
 chk_cmt="uvm_scoreboard (lsu_passive_agent log vs ref_model)",
 gen="Generate branch/jump/trap immediately followed (in program order) by load/store instructions, incl. while LSU wait states are active",
 gen_obj="riscv_ctrl_mem_mix_sequence",
 cov="Cover control-transfer x following-memory-instruction x wait-state combinations",
 cov_cg="ctrl_mem_mix_cg"),
dict(id="risc_lsu_09",
 desc="The data OBI interface has no error response signal; the TB memory always completes transactions successfully - no error stimulus is generated or expected.",
 note="The load_err/store_err paths in the RTL are tied inactive in this configuration (no PMP).",
 comp="lsu_agent"),
# ============================ DECODE / LEGALITY ============================
dict(id="risc_dec_00",
 desc="All RV32I base instructions are legal and must execute correctly: LUI, AUIPC, JAL, JALR, BEQ, BNE, BLT, BGE, BLTU, BGEU, LB, LH, LW, LBU, LHU, SB, SH, SW, ADDI, SLTI, SLTIU, XORI, ORI, ANDI, SLLI, SRLI, SRAI, ADD, SUB, SLL, SLT, SLTU, XOR, SRL, SRA, OR, AND. (FENCE / FENCE.I / ECALL / EBREAK are part of the base ISA but are omitted from the generated stimulus.)",
 note="Golden reference: an in-house RV32IM model connected to the uvm_scoreboard.",
 comp="uvm_scoreboard, ref_model",
 chk="check every retired RV32I instruction against the golden model: rd value, memory effects, and next-PC",
 chk_prop="sb_rv32i_result_match",
 chk_cmt="uvm_scoreboard (rvfi_monitor vs ref_model)",
 gen="Generate streams per instruction class with random registers (incl. x0 usages) and immediates incl. corner values",
 gen_obj="riscv_alu_sequence, riscv_upper_sequence",
 cov="Cover every RV32I mnemonic decoded/retired at least once (distinguish ADD/SUB, SRL/SRA via funct7)",
 cov_cg="rv32i_instr_cg"),
dict(id="risc_dec_01",
 desc="All 8 RV32M instructions are legal and must execute correctly: MUL, MULH, MULHSU, MULHU, DIV, DIVU, REM, REMU.",
 note="",
 comp="uvm_scoreboard, ref_model",
 chk="check every retired RV32M instruction against the golden model (rd value and timing class)",
 chk_prop="sb_rv32m_result_match",
 chk_cmt="uvm_scoreboard",
 gen="Generate mul/div/rem streams with random and corner operands (sign modes, zero, min/max, alternating patterns)",
 gen_obj="riscv_mul_sequence, riscv_div_sequence",
 cov="Cover every RV32M mnemonic at least once x operand corner classes",
 cov_cg="rv32m_instr_cg, m_operands_cg"),
dict(id="risc_dec_02",
 desc="Illegal instruction detection within the RV32I/M opcode space (verified against cv32e40p_decoder.sv illegal_insn conditions): any undefined encoding raises an illegal instruction exception, including:\n(a) undefined major opcodes;\n(b) a legal major opcode with an undefined funct3/funct7 combination;\n(c) reserved shift encodings: OP-IMM/OP with funct3=001/101 and imm[11:5] (funct7) other than 0000000 or 0100000.",
 note="Encodings of disabled extensions (FPU/atomic/CORE-V custom/CSR opcodes) are never generated at all - see risc_dec_04.",
 comp="uvm_scoreboard, if_passive_agent",
 chk="check that each injected illegal encoding is detected: the instruction retires to trap (no rd write, no memory request produced by it) and fetch redirects to mtvec base",
 chk_prop="sb_illegal_trap, exc_trap_base_prop",
 chk_cmt="uvm_scoreboard + SVA",
 gen="Generate items from each illegal category (a)-(c) with randomized filler bits; inject at random stream positions",
 gen_obj="riscv_illegal_sequence",
 cov="Cover each illegal category (a)-(c) at least once; cover illegal back-to-back and illegal during OBI wait-state windows",
 cov_cg="illegal_category_cg, illegal_context_cg"),
dict(id="risc_dec_03",
 desc="Register operands equal to x0 keep legality: e.g. ADD x0,rs1,rs2, loads with rd=x0, JAL x0 (no link) are legal and produce the standard no-write/no-link behavior (see risc_rf_00); encodings that are undefined remain illegal even with x0 fields.",
 note="",
 comp="uvm_scoreboard",
 chk="check via golden compare that x0-destination instructions retire with x0 unchanged and all other effects (e.g. JAL x0 still jumps) as per the ISA",
 chk_prop="sb_x0_zero, sb_pc_flow_match",
 chk_cmt="uvm_scoreboard",
 gen="Bias register selection to force rd=x0 and rs1/rs2=x0 across instruction classes",
 gen_obj="riscv_alu_sequence, riscv_corner_case_sequence (x0 mode)",
 cov="Cover x0 used as rd / rs1 / rs2 across each instruction class",
 cov_cg="x0_usage_cg"),
dict(id="risc_dec_04",
 desc="Omitted from stimulus (generation constraint): FENCE, FENCE.I, ECALL, EBREAK, WFI, MRET and all CSR instructions; interrupt and debug traffic; compressed instructions; all FPU / CORE-V custom / atomic instructions (including their opcodes as partial encodings).",
 note="Generation constraint only - no checkers or coverage are built for these.",
 comp="generation constraint (riscv_program)",
 gen="not generated",
 gen_obj="-"),
# ============================ ALU / SHIFTS =================================
dict(id="risc_alu_00",
 desc="Integer computational instructions (ADD/SUB/AND/OR/XOR/SLL/SRL/SRA/SLT/SLTU + I-forms, LUI, AUIPC) produce their result in 1 cycle; the EX->ID forwarding path gives a 0-cycle penalty for a back-to-back dependent ALU instruction; SLT/SLTU distinguish signed vs unsigned compare and SLTIU compares rs1 unsigned against the sign-extended immediate (per the RISC-V spec).",
 note="",
 comp="uvm_scoreboard",
 chk="check results via golden compare incl. forwarding chains (consumer equals producer value at distance 1,2,3)",
 chk_prop="sb_rv32i_result_match",
 chk_cmt="uvm_scoreboard",
 gen="Generate dependent ALU chains with producer/consumer register overlap on rs1-only, rs2-only, both; mix in x0",
 gen_obj="riscv_hazard_sequence (alu chain mode)",
 cov="Cover ALU op x operand corner sets (0, 1, -1, INT_MIN, INT_MAX, 0xAAAAAAAA/0x55555555) incl. signed/unsigned compare extreme pairs",
 cov_cg="alu_operands_cg"),
dict(id="risc_alu_01",
 desc="Shifts use a single-cycle barrel shifter; the shift amount shamt is operand_b[4:0] (register form) or imm[4:0]; SRA/SRAI replicate the sign bit; SLL/SRL shift in zeros. shamt=0 leaves the operand unchanged.",
 note="",
 comp="uvm_scoreboard",
 chk="check shift results via golden compare for every shamt corner and sign combination",
 chk_prop="sb_shift_result_match",
 chk_cmt="uvm_scoreboard",
 gen="Generate SLL/SRL/SRA/SLLI/SRLI/SRAI with shamt in {0,1,15,16,30,31} plus random, on operands: 1, MSB-set, 0x80000000, 0xFFFFFFFF, 0xAAAAAAAA",
 gen_obj="riscv_shift_sequence",
 cov="Cover shamt {0,1,15,16,31} x op x operand MSB pattern",
 cov_cg="shift_amount_cg"),
dict(id="risc_alu_02",
 desc="LUI writes imm[31:12]<<12; AUIPC writes PC + (imm<<12) - the result depends on the current PC (position-dependent behavior).",
 note="",
 comp="uvm_scoreboard",
 chk="check AUIPC results across different PC regions (low/high boot locations, right after jumps)",
 chk_prop="sb_upper_result_match",
 chk_cmt="uvm_scoreboard",
 gen="Generate LUI/AUIPC with imm corners (0, 1, 0x80000, 0xFFFFF, walking patterns); place AUIPC at varied PCs incl. right after taken branches/jumps",
 gen_obj="riscv_upper_sequence",
 cov="Cover AUIPC at diverse PC values (cross with branch-target regions)",
 cov_cg="upper_imm_cg"),
# ============================ M EXTENSION ==================================
dict(id="risc_m_00",
 desc="MUL executes in 1 cycle (32x32 single-cycle multiplier, lower 32 bits of the product).",
 note="",
 comp="uvm_scoreboard",
 chk="check MUL result == lower-32 product via golden compare",
 chk_prop="sb_mul_result_match",
 chk_cmt="uvm_scoreboard",
 gen="Generate MUL with corner operands (0, 1, -1, INT_MIN, INT_MAX, random 16x16-bit patterns that stress partial products)",
 gen_obj="riscv_mul_sequence",
 cov="Cover MUL operand corner classes",
 cov_cg="m_operands_cg"),
dict(id="risc_m_01",
 desc="MULH/MULHSU/MULHU take 5 cycles (multicycle FSM STEP0->STEP1->STEP2->FINISH in rtl cv32e40p_mult.sv) and stall EX meanwhile; they return the upper 32 bits for signed x signed, signed x unsigned, unsigned x unsigned operands respectively.",
 note="",
 comp="uvm_scoreboard",
 chk="check upper-half products for all three sign modes via golden compare; check no other write-back occurs during the stall window",
 chk_prop="sb_mulh_result_match, sb_no_spurious_wb",
 chk_cmt="uvm_scoreboard (+ rvfi_monitor: single write per retire)",
 gen="Generate mulh/mulhsu/mulhu x operand sign corners: (INT_MIN,-1), (INT_MAX,INT_MAX), (0x80000000,1), (0xFFFFFFFF,0xFFFFFFFF), zero operands",
 gen_obj="riscv_mul_sequence (mulh mode)",
 cov="Cover sign-mode x operand corners; cover a dependent consumer immediately after mulh",
 cov_cg="mulh_corners_cg, multicycle_hazard_cg"),
dict(id="risc_m_02",
 desc="DIV/DIVU/REM/REMU are iterative with early termination: latency is 3..35 cycles depending on the number of leading zeros of operand b (the divisor); minimum 3 cycles when the divisor has no leading zeros (e.g. 0x80000000), maximum 35 when the divisor is 0; EX stalls meanwhile.",
 note="Early-termination loop verified in rtl cv32e40p_alu_div.sv (the divisor is pre-shifted).",
 comp="uvm_scoreboard, lsu_passive_agent",
 chk="check div/rem results via golden compare AND measured retire-latency within 3..35 cycles at zero wait states",
 chk_prop="sb_div_result_match, sb_div_latency_range",
 chk_cmt="uvm_scoreboard (latency measured between issue and retire at zero wait states)",
 gen="Generate divisor leading-zero-count bins (0, 1, 8, 16, 31, 32(=divisor 0)) to sweep the latency spectrum; random dividend/divisor",
 gen_obj="riscv_div_sequence",
 cov="Cover div latency bins: 3, 4-10, 11-20, 21-34, 35 cycles per op",
 cov_cg="div_latency_cg"),
dict(id="risc_m_03",
 desc="Special division results per the RISC-V spec: divide-by-zero -> quotient = -1 (all ones) for DIV/DIVU; remainder = dividend for REM/REMU. Signed overflow (DIV -2^31 / -1) -> quotient = -2^31, REM -2^31 / -1 -> 0. The REM sign follows the dividend; REMU is unsigned.",
 note="",
 comp="uvm_scoreboard",
 chk="check the exact special-case values via golden compare (directed vectors)",
 chk_prop="sb_div_corner_results",
 chk_cmt="uvm_scoreboard",
 gen="Directed corner matrix: {dividend in {0, 1, -1, INT_MIN, INT_MAX, random}} x {divisor in {0, 1, -1, INT_MIN, INT_MAX}} for all four ops",
 gen_obj="riscv_div_corner_sequence",
 cov="Cover all corner cells for DIV/DIVU/REM/REMU incl. div0 and overflow",
 cov_cg="div_corners_cg"),
dict(id="risc_m_04",
 desc="A multicycle instruction (MULH/DIV/REM) that is older than a taken branch always completes and writes back normally, even when the flush of the younger path lands in the same window - only IF/ID (the younger stages) are flushed.",
 note="Consistent with the databook pipeline chapter and the controller FSM.",
 comp="uvm_scoreboard",
 chk="check the multicycle result is written back and the branch-target path retires correctly (scenario test)",
 chk_prop="sb_multicycle_plus_branch",
 chk_cmt="uvm_scoreboard",
 gen="Generate mulh/div followed at distance 1-2 by a taken branch (with and without RAW dependency between them)",
 gen_obj="riscv_ctrl_mix_sequence",
 cov="Cover mulh/div x following taken branch x dependency distance",
 cov_cg="multicycle_branch_cg"),
# ============================ PIPELINE / HAZARDS ===========================
dict(id="risc_haz_00",
 desc="RAW forwarding: ALU/MUL/DIV results in EX are forwarded to ID-stage operands (ports a and b), giving a 0-cycle penalty for back-to-back dependent instructions; the consumer reads correct producer values at distance 1, 2, 3.",
 note="Forwarding muxes verified in rtl cv32e40p_id_stage.sv (reg_d_ex/alu_is_reg_a/b/c).",
 comp="uvm_scoreboard",
 chk="check consumer results via golden compare across dependency distances and both operand slots",
 chk_prop="sb_rv32i_result_match",
 chk_cmt="uvm_scoreboard (guaranteed through dense dependent streams)",
 gen="Generate RAW chains: producer->consumer distance 1/2/3, on rs1 / rs2 / both, incl. chains of length >=4",
 gen_obj="riscv_hazard_sequence",
 cov="Cross producer type (alu/mul/div) x distance {1,2,3} x slot {rs1,rs2,both}",
 cov_cg="raw_distance_cg"),
dict(id="risc_haz_01",
 desc="Load-use hazard: an instruction consuming a register written by the immediately preceding load is stalled exactly 1 cycle (controller load_stall + deassert_we in rtl cv32e40p_controller.sv); no wrong value is read and no spurious write occurs during the stall.",
 note="At 1-cycle distance only; >=2-distance consumers are not stalled.",
 comp="uvm_scoreboard, rvfi_monitor",
 chk="check the consumer receives the load data (golden compare) and the retire spacing shows the single stall cycle at zero wait states",
 chk_prop="sb_load_use_correct, sb_load_use_1cycle",
 chk_cmt="uvm_scoreboard",
 gen="Generate load->consumer pairs (distance exactly 1 and exactly 2) across all load types and consumer classes (incl. branch/jalr consumer)",
 gen_obj="riscv_hazard_sequence (load_use mode)",
 cov="Cover load type x consumer class x distance {1,2}",
 cov_cg="load_use_cg"),
dict(id="risc_haz_02",
 desc="JALR data hazard: a JALR whose rs1 is produced by the immediately preceding instruction is stalled 1 cycle (jr_stall) before computing its target; the target must be (rs1+imm) & ~1.",
 note="",
 comp="uvm_scoreboard",
 chk="check JALR target correctness when rs1 comes from an ALU result and from a load result, via golden compare of the PC stream",
 chk_prop="sb_jalr_target_match",
 chk_cmt="uvm_scoreboard",
 gen="Generate producer->JALR pairs: ALU->JALR and LW->JALR at distance 1,2,3; odd immediates to exercise the &~1 clearing",
 gen_obj="riscv_branch_sequence (jalr hazard mode)",
 cov="Cover producer type x distance for JALR targets",
 cov_cg="jr_hazard_cg"),
dict(id="risc_haz_03",
 desc="WAW write-port arbitration: a load in WB and a younger ALU/MUL/DIV instruction in EX may write the same rd in the same cycle; the register file resolves it with port-b (EX) priority, i.e. the architecturally younger instruction wins (verified in rtl cv32e40p_register_file_ff.sv: the we_b write is checked before we_a).",
 note="",
 comp="uvm_scoreboard",
 chk="check that after such a collision the final rd value equals the younger instruction's result (golden model final-state compare + targeted readback)",
 chk_prop="sb_waw_younger_wins",
 chk_cmt="uvm_scoreboard",
 gen="Generate lw rd,<-mem followed at distance 1..3 by an ALU/MUL/DIV op writing the same rd; sweep rd incl. x0 exclusion semantics; include a misaligned-load producer variant (pair completes in WB while the younger EX write lands)",
 gen_obj="riscv_waw_sequence",
 cov="Cover collision window positions (load WB overlapping the EX write)",
 cov_cg="waw_cg"),
dict(id="risc_haz_04",
 desc="Control-flush cleanliness: instructions younger than a taken branch / jump / trap never produce architectural side effects (no register write, no memory request).",
 note="",
 comp="uvm_scoreboard, lsu_passive_agent",
 chk="check per retire stream + data-bus log: nothing from the flushed path appears (companion to risc_if_06 and risc_lsu_08)",
 chk_prop="sb_flush_clean, sb_lsu_trans_stream_match",
 chk_cmt="uvm_scoreboard"),
# ============================ REGISTER FILE =================================
dict(id="risc_rf_00",
 desc="x0 is hardwired to zero: reads always return 0 and writes to x0 are ignored (x0 has no flip-flops), even when a load targets x0.",
 note="",
 comp="uvm_scoreboard, rvfi_monitor",
 chk="check x0==0 after every retired instruction (monitor side) and that x0-source operands are read as 0 (covered by the golden compare)",
 chk_prop="sb_x0_zero",
 chk_cmt="uvm_scoreboard / optional hierarchical SVA on RF mem[0]"),
dict(id="risc_rf_01",
 desc="All 31 general-purpose registers x1..x31 are implemented (the FF register file resets to 0 at rst_ni==0) with 3 read ports and 2 write ports; reads happen in ID, writes from EX and WB.",
 note="Reset-zero is an implementation property of the FF-based register file - checked once at test start; it is not an ISA requirement.",
 comp="uvm_scoreboard",
 chk="check initial reads of unwritten registers return 0 (first test only, implementation-specific), afterwards golden compare",
 chk_prop="sb_rf_reset_zero_opt",
 chk_cmt="uvm_scoreboard; optional, documented as implementation-specific",
 gen="Sweep rd/rs1/rs2 across all 32 registers in every instruction class",
 gen_obj="riscv_alu_sequence (reg sweep)",
 cov="Cover every x1..x31 as rd, rs1, rs2 across instruction classes",
 cov_cg="reg_access_cg"),
# ============================ RESET SCENARIOS ==============================
dict(id="risc_rst_00",
 desc="Reset re-assertion during an outstanding instruction-fetch transaction: core and TB slave both drop the transaction; after re-enabling, the core re-boots from boot_addr_i with a clean pipeline; no stale rvalid may be consumed after reset.",
 note="TB OBI slaves implement a reset that clears their outstanding queues.",
 comp="sys_ctrl_agent, if_agent, uvm_scoreboard",
 chk="check post-reset re-boot: first fetch == boot_addr_i, the scoreboard re-syncs, zero mismatches afterwards",
 chk_prop="sb_reset_resync",
 chk_cmt="uvm_scoreboard",
 gen="Inject reset at random times synchronized to IF wait-state windows",
 gen_obj="sys_ctrl_reset_inject_sequence",
 cov="(covered under risc_sys_02 reset_context_cg)",
 cov_cg="reset_context_cg"),
dict(id="risc_rst_01",
 desc="Reset re-assertion during outstanding data transactions (load/store granted but rvalid pending, incl. mid misaligned pair).",
 note="",
 comp="sys_ctrl_agent, lsu_agent, uvm_scoreboard",
 chk="check post-reset re-boot and no corruption of the dmem image (stores before reset kept, partial pair never completed)",
 chk_prop="sb_reset_resync, sb_store_mem_match",
 chk_cmt="uvm_scoreboard",
 gen="Inject reset during LSU wait-state windows (misaligned pair in flight as a targeted sub-case)",
 gen_obj="sys_ctrl_reset_inject_sequence + riscv_lsu_misaligned_sequence background",
 cov="(covered under risc_sys_02 reset_context_cg)",
 cov_cg="reset_context_cg"),
dict(id="risc_rst_02",
 desc="Reset re-assertion during a multicycle DIV/REM or MULH execution, and during a branch-flush window.",
 note="",
 comp="sys_ctrl_agent, uvm_scoreboard",
 chk="check post-reset re-boot; no write-back from the killed multicycle instruction appears after reset",
 chk_prop="sb_reset_resync, sb_no_spurious_wb",
 chk_cmt="uvm_scoreboard",
 gen="Inject reset during div/mulh iterations and immediately after a taken branch",
 gen_obj="sys_ctrl_reset_inject_sequence + riscv_div_sequence background",
 cov="(covered under risc_sys_02 reset_context_cg)",
 cov_cg="reset_context_cg"),
# ============================ ENVIRONMENT (TB SLAVES) ======================
dict(id="risc_env_00",
 desc="The TB includes its own instruction memory and data memory models working as OBI slaves. The instruction memory is pre-loaded with a generated or directed program before the core is enabled; the data memory is pre-loaded with a data pool. All memory words are deterministically initialized, so loads of unwritten locations are reproducible and match the golden model.",
 note="",
 comp="if_agent (instr_mem_model), lsu_agent (data_mem_model), riscv_program"),
dict(id="risc_env_01",
 desc="OBI slave response features: per-transaction gnt delay (0..K), rvalid delay (1..L); operating modes: zero-wait, random, long-stall bursts, gnt-always-high; both buses configurable independently.",
 note="",
 comp="if_agent, lsu_agent",
 chk="check slave protocol self-guards (never two rvalid for one grant; never rvalid with an empty outstanding queue; rdata stable at the rvalid cycle)",
 chk_prop="env_slave_protocol_prop",
 chk_cmt="Assertions inside if_agent / lsu_agent drivers",
 gen="Seed sweeping: short/medium/long delay distributions, alternating fast/slow window lengths, simultaneous stalls on both buses",
 gen_obj="obi_memory_sequence",
 cov="Cross IF-stall x LSU-stall activity windows (parallel pressure)",
 cov_cg="dual_bus_stress_cg"),
dict(id="risc_env_02",
 desc="Test teardown: at end of test all outstanding responses are delivered (memory drains), the retire stream is checked complete against expectations, and the final GPR + memory state is compared; a global watchdog timeout catches any hung core.",
 note="",
 comp="uvm_scoreboard, top_tb",
 chk="check end-of-test flush: outstanding==0 on both buses, final register file contents == golden, final dmem == golden, no test timeout",
 chk_prop="sb_final_state_match, env_teardown_check",
 chk_cmt="uvm_scoreboard"),
dict(id="risc_scope_00",
 desc="Features outside the verification goal - kept inactive (static tie-offs) or never generated, listed here only as constraints: C-extension internals (aligner/compressed decoder), CSR instructions and CSR state, interrupts, debug, sleep unit / wfi / elw, FPU and FP CSRs, CORE-V custom (PULP/CLUSTER) instructions and CSRs, atomics / PMP / user mode, performance counters, FENCE / ECALL / EBREAK / MRET.",
 note="No checkers or coverage are built for these.",
 comp="-"),
]
# ---------------------------------------------------------------------------
# Test list (template sheet 'test list': test name | sequance run | stimuls generated)
# ---------------------------------------------------------------------------
TESTS = [
 ("risc_reset_test",            "sys_ctrl_init_sequence",
  "Apply reset (random delay/hold), program boot_addr_i/mtvec_addr_i at corner values, toggle fetch_enable at 0/1/N cycles; check boot flow and output inactivity; repeat with a 2nd reset mid-idle. Multiple seeds."),
 ("risc_fetch_enable_stress_test", "sys_ctrl_init_sequence (fe_delay mode)",
  "Sweep fetch_enable delays incl. >8 cycles; verify no fetch before enable and permanent activity after."),
 ("risc_alu_r_type_test",       "riscv_alu_sequence",
  "Generate only R-type integer ops (ADD,SUB,SLL,SLT,SLTU,XOR,SRL,SRA,OR,AND) with random rs1/rs2/rd and operand corner pools. ~2000 instrs x 10 seeds."),
 ("risc_alu_i_type_test",       "riscv_alu_sequence",
  "Generate only I-type ALU ops (ADDI,SLTI,SLTIU,XORI,ORI,ANDI) with corner immediates (0,1,-1,INT11_MIN,INT11_MAX). ~2000 instrs x 10 seeds."),
 ("risc_shift_test",            "riscv_shift_sequence",
  "SLL/SRL/SRA/SLLI/SRLI/SRAI with shamt {0,1,15,16,30,31} and operand MSB patterns; check barrel-shifter corners. ~1500 instrs."),
 ("risc_upper_test",            "riscv_upper_sequence",
  "LUI/AUIPC with immediate corners placed at diverse PCs incl. right after taken branches/jumps. ~800 instrs."),
 ("risc_load_store_aligned_test", "riscv_lsu_sequence",
  "All aligned LB/LH/LW/LBU/LHU/SB/SH/SW across offsets and data corners; zero-wait dmem. ~2000 instrs."),
 ("risc_load_sign_test",        "riscv_lsu_sequence (sign pool)",
  "LB/LBU/LH/LHU loads where the target byte/half MSB toggles 0/1 at every offset; verify sign vs zero extension. ~1000 instrs."),
 ("risc_misaligned_test",       "riscv_lsu_misaligned_sequence",
  "lw/sw at offsets 1/2/3, lh/sh at offset 3 (two-beat) and 1/2 (single-beat); check 2-transaction split, order, be patterns, merged data. ~1200 accesses."),
 ("risc_mem_b2b_test",          "riscv_mem_b2b_sequence",
  "Back-to-back st->ld (same addr / lane-overlap), ld->st, st->st, ld->ld; shadow-memory consistency. ~1500 accesses."),
 ("risc_branch_test",           "riscv_branch_sequence",
  "All 6 branch conditions, taken/not-taken, fwd/back targets, operand relations incl. INT_MIN/INT_MAX extremes. ~2000 branches."),
 ("risc_jump_test",             "riscv_branch_sequence (jump mode)",
  "JAL fwd/back with link x0/x1/x5; JALR with odd/even immediates (& ~1 rule), various base registers. ~1500 jumps."),
 ("risc_jalr_hazard_test",      "riscv_branch_sequence (jalr hazard mode)",
  "ALU->JALR and LW->JALR producer pairs at distance 1/2/3 to exercise jr_stall. ~800 pairs."),
 ("risc_mul_test",              "riscv_mul_sequence",
  "MUL/MULH/MULHSU/MULHU with sign-corner matrix (0,1,-1,INT_MIN,INT_MAX,0xAAAAAAAA). ~1500 ops."),
 ("risc_div_test",              "riscv_div_sequence",
  "DIV/DIVU/REM/REMU with divisor leading-zero sweep (latency spectrum 3..35) and random operands. ~1500 ops."),
 ("risc_div_corner_test",       "riscv_div_corner_sequence",
  "Directed corner matrix: div-by-zero for all 4 ops, DIV/REM overflow (-2^31/-1), dividend 0, divisor +-1. Exhaustive small set."),
 ("risc_illegal_instr_test",    "riscv_illegal_sequence",
  "Inject illegal encodings of every category (a)-(c) at random positions; check trap redirect, no side effects, resume at handler. ~1000 injections."),
 ("risc_illegal_context_test",  "riscv_illegal_sequence (context mode)",
  "Illegal injections back-to-back, during IF wait-state windows, and immediately after taken branches/jumps. ~800 injections."),
 ("risc_hazard_raw_test",       "riscv_hazard_sequence",
  "Dense RAW chains distance 1/2/3 across producer types and operand slots, incl. >=4-long chains. ~2000 instrs."),
 ("risc_load_use_test",         "riscv_hazard_sequence (load_use mode)",
  "Load->consumer at distance 1 and 2 for every load type x consumer class (alu/branch/jalr/store-data). ~1200 pairs."),
 ("risc_waw_test",              "riscv_waw_sequence",
  "LW rd followed by ALU/MUL/DIV writing the same rd at 1..3 spacing (incl. misaligned-load producer); targeted readback of rd afterwards. ~1000 scenarios."),
 ("risc_multicycle_branch_test","riscv_ctrl_mix_sequence",
  "MULH/DIV followed at distance 1-2 by taken branches (with/without RAW between them); also control-transfer x following-load/store mixes. ~1000 scenarios."),
 ("risc_obi_waitstate_test",    "obi_memory_sequence",
  "Legal instruction/data streams under randomized gnt/rvalid delays on both buses (independent), short and medium distributions. x 10 seeds."),
 ("risc_obi_stall_stress_test", "obi_memory_sequence (stall mode)",
  "Long-stall bursts forced during mem-heavy windows to saturate 2-outstanding LSU and 2-outstanding prefetch; stall during the misaligned 2nd beat targeted."),
 ("risc_gnt_always_high_test",  "obi_memory_sequence (gnt_always_high mode)",
  "gnt held high for long windows incl. while no request is pending, on both IF and LSU channels."),
 ("risc_reset_inject_test",     "sys_ctrl_reset_inject_sequence",
  "Re-assert reset during: IF outstanding, LSU outstanding, misaligned pair mid-flight, DIV iteration, branch flush; then full re-boot and continue. Multiple seeds."),
 ("risc_random_mix_test",       "riscv_random_mix_sequence",
  "Fully random RV32IM program streams (weighted classes incl. illegals ratio ~2%) + random OBI delays on both buses; main regression test. ~5000 instrs x 30 seeds."),
]

# ---------------------------------------------------------------------------
# HTML generation (template-faithful)
# ---------------------------------------------------------------------------

def esc(s):
    s = html.escape(str(s), quote=True)
    return s.replace("\n", "<br>")

def load_template(fname):
    raw = open(os.path.join(TEMPLATE_DIR, fname), encoding="utf-8", errors="ignore").read()
    style = re.search(r'(<style type="text/css">.*?</style>)', raw, re.S).group(1)
    thead = re.search(r'(<thead><tr>.*?</tr></thead>)', raw, re.S).group(1)
    tbody = re.search(r'<tbody>(.*?)</tbody>', raw, re.S).group(1)
    rows = re.findall(r'(<tr style="height: \d+px">.*?</tr>)', tbody, re.S)
    row1, row2 = rows[0], rows[1]
    return style, thead, row1, row2

def make_row(prefix, rownum, cells, cell_classes, height):
    th = (f'<th id="{prefix}R{rownum-1}" style="height: {height}px;" class="row-headers-background">'
          f'<div class="row-header-wrapper" style="line-height: {height}px">{rownum}</div></th>')
    tds = "".join(
        f'<td class="{cls}">{esc(c)}</td>' if c else f'<td class="{cls}"></td>'
        for c, cls in zip(cells, cell_classes))
    fillers = "".join("<td></td>" for _ in range(NUM_COLS - len(cells)))
    return f'<tr style="height: {height}px">{th}{tds}{fillers}</tr>'

def est_height(texts, base=18):
    mx = 1
    for t in texts:
        if not t: continue
        for seg in str(t).split("\n"):
            mx = max(mx, -(-len(seg) // 95))
    return max(base, 13 * mx + 6)

def build_sheet(fname, data_cells, cell_classes, base_h=18):
    style, thead, row1, row2 = load_template(fname)
    prefix = re.search(r'id="(\d+?)(?:R0)?"', row1).group(1)
    title_row = re.sub(r'>DW_apb<', f'>{TITLE}<', row1)
    rows = [title_row, row2]
    for i, cells in enumerate(data_cells):
        rows.append(make_row(prefix, i + 3, cells, cell_classes, est_height(cells, base_h)))
    out = ('<meta http-equiv="Content-Type" content="text/html; charset=utf-8">'
           '<link type="text/css" rel="stylesheet" href="resources/sheet.css" >'
           + style +
           '<div class="ritz grid-container" dir="ltr"><table class="waffle" cellspacing="0" cellpadding="0">'
           + thead + "<tbody>" + "".join(rows) + "</tbody></table></div>")
    dst = os.path.join(HERE, fname)
    open(dst, "w", encoding="utf-8").write(out)
    print(f"wrote {fname}: {len(data_cells)} data rows")

def main():
    os.makedirs(os.path.join(HERE, "resources"), exist_ok=True)
    shutil.copyfile(os.path.join(TEMPLATE_DIR, "resources", "sheet.css"),
                    os.path.join(HERE, "resources", "sheet.css"))

    # ---- System.html : ID | Design Requirement Description | note | component name
    build_sheet("System.html",
        [(r["id"], r["desc"], r.get("note", ""), r.get("comp", "")) for r in R],
        ["s6", "s6", "s6", "s6"])

    # ---- Generation_.html : ID | Design Requirement Description | Generation | component/Object name
    build_sheet("Generation_.html",
        [(r["id"], r["desc"], r["gen"], r.get("gen_obj", "")) for r in R if r.get("gen")],
        ["s6", "s6", "s7", "s7"])

    # ---- Checking_.html : ID | Design Requirement Description | check | property name | comment
    build_sheet("Checking_.html",
        [(r["id"], r["desc"], r["chk"], r.get("chk_prop", ""), r.get("chk_cmt", "")) for r in R if r.get("chk")],
        ["s6", "s6", "s7", "s7", "s7"])

    # ---- Coverage_.html : ID | Design Requirement Description | Coverage | covergroup
    build_sheet("Coverage_.html",
        [(r["id"], r["desc"], r["cov"], r.get("cov_cg", "")) for r in R if r.get("cov")],
        ["s7", "s7", "s8", "s9"])

    # ---- test list.html : test name | sequance run | stimuls generated
    build_sheet("test list.html", TESTS, ["s5", "s5", "s5"], base_h=16)

if __name__ == "__main__":
    main()
